# Generated by Django 5.1 on 2024-10-04 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_livro_titulo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='Livro',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Category',
        ),
    ]
